### ISSUE TITLE
Feat: lastUpdate is missing

### ISSUE THREAD

**Issue by zongqichen** [cap-js/ord#85]
The current implementation doesn't contain lastUpdate filed, which is important to UCL (Unified Customer Landscape). UCL has a function to decide whether update the ord document backend by version and lastUpdate fileds.

**Comment by Fannon** [comment]
Good catch! 

First idea: We could just create a `new Date()` on startup of the CAP server. Then as long as the server runs, it will not change and UCL will not fetch metadata again. This works fine as long as the metadata is static - as it cannot change while the server is running. 

If you want `lastUpdated` to not update everytime you restart the server ,you have to manually set it via `@ORD.Extensions`. (this should already work). 

Once we have run-time tenant specific ORD metadata, the `lastUpdate` situation gets more complicated because it needs to be updated everytime the resource has been changed at run-time. But for now this is not supported and we should first improve the static metadata case.
